/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Actividades;
import Logica.LogicaActividades;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GIU_CrearActividadExtra extends javax.swing.JFrame {

    /**
     * Creates new form GIU_CrearActividadExtra
     */
    Actividades ObjAct = new Actividades();
    LogicaActividades ObjLogAct = new LogicaActividades();

    public GIU_CrearActividadExtra() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jFechaFin.getDateEditor().setEnabled(false);
        this.jFechaInicio.getDateEditor().setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreActividad = new javax.swing.JTextField();
        BotonValidar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFechaInicio = new com.toedter.calendar.JDateChooser();
        jFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxOpicionActividad = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jBotonCancelar = new javax.swing.JButton();
        jBotonSalir = new javax.swing.JButton();
        jBotonCrearActividad = new javax.swing.JButton();
        jBotonConfirmar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButtonConAporteEconómico = new javax.swing.JRadioButton();
        jRadioButtonSinAporteEconómico = new javax.swing.JRadioButton();
        jTextAporteEconomico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(49, 147, 176));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CREAR ACTIVIDADES EXTRA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jLabel6.setText("Nombre de la actividad");

        NombreActividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreActividadKeyTyped(evt);
            }
        });

        BotonValidar.setText("VALIDAR");
        BotonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonValidarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de inicio");

        jLabel4.setText("Fecha de fin");

        jFechaInicio.setDateFormatString("yyyy-MM-dd");

        jFechaFin.setDateFormatString("yyyy-MM-dd");

        jLabel8.setText("Tipo de actividad");

        jComboBoxOpicionActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opción", "Deportes", "Excursiones", "Social", "Viajes fin de curso", "otros" }));
        jComboBoxOpicionActividad.setEnabled(false);
        jComboBoxOpicionActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpicionActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxOpicionActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxOpicionActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBotonCancelar.setText("Cancelar");
        jBotonCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(49, 147, 176), new java.awt.Color(49, 147, 176)));
        jBotonCancelar.setEnabled(false);
        jBotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCancelarActionPerformed(evt);
            }
        });

        jBotonSalir.setText("Volver");
        jBotonSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(49, 147, 176), new java.awt.Color(49, 147, 176)));
        jBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSalirActionPerformed(evt);
            }
        });

        jBotonCrearActividad.setText("Crear Actividad");
        jBotonCrearActividad.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(49, 147, 176), new java.awt.Color(49, 147, 176)));
        jBotonCrearActividad.setEnabled(false);
        jBotonCrearActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCrearActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jBotonCrearActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jBotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonCrearActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBotonConfirmar.setText("Confirmar");
        jBotonConfirmar.setEnabled(false);
        jBotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConfirmarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonConAporteEconómico);
        jRadioButtonConAporteEconómico.setText("Con aporte económico");
        jRadioButtonConAporteEconómico.setEnabled(false);
        jRadioButtonConAporteEconómico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConAporteEconómicoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSinAporteEconómico);
        jRadioButtonSinAporteEconómico.setText("Sin aporte economico");
        jRadioButtonSinAporteEconómico.setEnabled(false);
        jRadioButtonSinAporteEconómico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSinAporteEconómicoActionPerformed(evt);
            }
        });

        jTextAporteEconomico.setEnabled(false);
        jTextAporteEconomico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAporteEconomicoKeyTyped(evt);
            }
        });

        jLabel7.setText("Dólares");

        jLabel5.setText("Costo de la inscripcion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextAporteEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jRadioButtonConAporteEconómico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonSinAporteEconómico)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSinAporteEconómico)
                    .addComponent(jRadioButtonConAporteEconómico))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAporteEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Microsoft Access_96px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonValidar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBotonConfirmar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonValidar)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBotonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSalirActionPerformed
        // TODO add your handling code here:
        GIU_Administrador ObjIA = new GIU_Administrador();
        int x = JOptionPane.showConfirmDialog(null, "¿Desea regresar?", "Los datos ingresados no se guardarán", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            ObjIA.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBotonSalirActionPerformed

    private void jComboBoxOpicionActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpicionActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpicionActividadActionPerformed

    private void jBotonCrearActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCrearActividadActionPerformed
        // TODO add your handling code here:

        if (this.jTextAporteEconomico.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El campo de aporte económico esta vacio");
        } else if (this.jComboBoxOpicionActividad.getSelectedItem().equals("Elija una opción")) {
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de actividad");
        } else {
            try {
                Calendar fecha = new GregorianCalendar();

                int mesActual = fecha.get(Calendar.MONTH) + 1;
                int diaActual = fecha.get(Calendar.DAY_OF_MONTH);

                String diaInicio = Integer.toString(this.jFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mesInicio = Integer.toString(this.jFechaInicio.getCalendar().get(Calendar.MONTH) + 1);
                String yearInicio = Integer.toString(this.jFechaInicio.getCalendar().get(Calendar.YEAR));
                String fechaInicio = (yearInicio + "-" + mesInicio + "-" + diaInicio);

                String diaFin = Integer.toString(this.jFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mesFin = Integer.toString(this.jFechaFin.getCalendar().get(Calendar.MONTH) + 1);
                String yearFin = Integer.toString(this.jFechaFin.getCalendar().get(Calendar.YEAR));

                if (Integer.parseInt(mesFin) >= Integer.parseInt(mesInicio) && Integer.parseInt(diaFin) >= Integer.parseInt(diaInicio) && Integer.parseInt(mesInicio) >= mesActual && Integer.parseInt(diaInicio) >= diaActual) {
                    String fechaFin = (yearFin + "-" + mesFin + "-" + diaFin);

                    ObjAct.setFechaInicio(Date.valueOf(fechaInicio));
                    ObjAct.setFechaFinal(Date.valueOf(fechaFin));
                    ObjAct.setTipoActividad(this.jComboBoxOpicionActividad.getSelectedItem().toString());
                    ObjAct.setNombreActividad(this.NombreActividad.getText().toUpperCase());
                    ObjAct.setAporteEconomico(Double.parseDouble(this.jTextAporteEconomico.getText()));
                    if (ObjLogAct.InsertarActividades(ObjAct)) {
                        JOptionPane.showMessageDialog(null, "Se registró correctamente en la base de datos");
                        this.NombreActividad.setText("");
                        this.jComboBoxOpicionActividad.setSelectedIndex(0);
                        this.jBotonCrearActividad.setEnabled(false);
                        this.NombreActividad.setEnabled(true);
                        this.jTextAporteEconomico.setText("");
                        this.jTextAporteEconomico.setEnabled(false);
                        this.jRadioButtonConAporteEconómico.setEnabled(false);
                        this.jRadioButtonSinAporteEconómico.setEnabled(false);
                        this.jComboBoxOpicionActividad.setEnabled(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Las fechas introducidas son incorrectas, debe seleccionar fechas igual o superiores a la de hoy.");
                }
            } catch (NullPointerException x) {
                JOptionPane.showMessageDialog(null, "Introduzca las fechas de inicio y fin de la actividad");
            }

        }

    }//GEN-LAST:event_jBotonCrearActividadActionPerformed

    private void jRadioButtonConAporteEconómicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConAporteEconómicoActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButtonConAporteEconómico.isSelected()) {
            this.jTextAporteEconomico.setText("");
            this.jTextAporteEconomico.setEnabled(true);
            this.NombreActividad.setEnabled(false);
            this.jBotonCrearActividad.setEnabled(true);
            this.jBotonCrearActividad.setEnabled(true);
            this.jBotonCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonConAporteEconómicoActionPerformed

    private void jRadioButtonSinAporteEconómicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSinAporteEconómicoActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButtonSinAporteEconómico.isSelected()) {
            this.jTextAporteEconomico.setEnabled(false);
            this.jTextAporteEconomico.setText("0.0");
            this.NombreActividad.setEnabled(false);
            this.jBotonCrearActividad.setEnabled(true);
            this.jBotonCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonSinAporteEconómicoActionPerformed

    private void jTextAporteEconomicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAporteEconomicoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO NÚMEROS");
        }
    }//GEN-LAST:event_jTextAporteEconomicoKeyTyped

    private void NombreActividadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreActividadKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
        if (Character.isLowerCase(validar)) { // SOLO MAYÚSCULAS
            String cad = ("" + validar).toUpperCase();
            validar = cad.charAt(0);
            evt.setKeyChar(validar);
        }

    }//GEN-LAST:event_NombreActividadKeyTyped

    private void BotonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonValidarActionPerformed
        // TODO add your handling code here:
        ObjAct.setNombreActividad(this.NombreActividad.getText());
        if (ObjAct.getNombreActividad().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Introduzca un nombre a la actividad");
        } else {
            if (this.BuscarActividad(ObjAct)) {
                this.NombreActividad.setEnabled(false);
                this.jBotonCancelar.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "¡PUEDES REGISTRAR ESTA ACTIVIDAD!");
                this.jComboBoxOpicionActividad.setEnabled(true);
                this.jBotonConfirmar.setEnabled(true);

            } else {

                JOptionPane.showMessageDialog(rootPane, "¡YA EXISTE ESTA ACTIVIDAD!");

            }
        }


    }//GEN-LAST:event_BotonValidarActionPerformed

    private void jBotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCancelarActionPerformed
        // TODO add your handling code here:
        this.NombreActividad.setText("");
        this.jComboBoxOpicionActividad.setSelectedIndex(0);
        this.jBotonCrearActividad.setEnabled(false);
        this.NombreActividad.setEnabled(true);
        this.jTextAporteEconomico.setText("");
        this.jTextAporteEconomico.setEnabled(false);
        this.jRadioButtonConAporteEconómico.setEnabled(false);
        this.jRadioButtonSinAporteEconómico.setEnabled(false);
        this.jComboBoxOpicionActividad.setEnabled(false);
        this.jBotonConfirmar.setEnabled(false);
    }//GEN-LAST:event_jBotonCancelarActionPerformed

    private void jBotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConfirmarActionPerformed
        // TODO add your handling code here:
        if (this.jComboBoxOpicionActividad.getSelectedItem().equals("Elija una opción")) {
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de actividad");
        } else {
            try {
                Calendar fecha = new GregorianCalendar();

                int mesActual = fecha.get(Calendar.MONTH) + 1;
                int diaActual = fecha.get(Calendar.DAY_OF_MONTH);

                String diaInicio = Integer.toString(this.jFechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mesInicio = Integer.toString(this.jFechaInicio.getCalendar().get(Calendar.MONTH) + 1);
                String yearInicio = Integer.toString(this.jFechaInicio.getCalendar().get(Calendar.YEAR));
                String fechaInicio = (yearInicio + "-" + mesInicio + "-" + diaInicio);

                String diaFin = Integer.toString(this.jFechaFin.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mesFin = Integer.toString(this.jFechaFin.getCalendar().get(Calendar.MONTH) + 1);
                String yearFin = Integer.toString(this.jFechaFin.getCalendar().get(Calendar.YEAR));

                if (Integer.parseInt(mesFin) >= Integer.parseInt(mesInicio) && Integer.parseInt(diaFin) >= Integer.parseInt(diaInicio) && Integer.parseInt(mesInicio) >= mesActual && Integer.parseInt(diaInicio) >= diaActual) {
                    String fechaFin = (yearFin + "-" + mesFin + "-" + diaFin);
                    JOptionPane.showMessageDialog(null, "La fecha y tipo de actividad son correctas");
                    this.jRadioButtonConAporteEconómico.setEnabled(true);
                    this.jRadioButtonSinAporteEconómico.setEnabled(true);
                    this.jComboBoxOpicionActividad.setEnabled(false);
                    

                } else {
                    JOptionPane.showMessageDialog(null, "Las fechas introducidas son incorrectas, debe seleccionar fechas igual o superiores a la de hoy.");
                }
            } catch (NullPointerException x) {
                JOptionPane.showMessageDialog(null, "Introduzca las fechas de inicio y fin de la actividad");
            }

        }
    }//GEN-LAST:event_jBotonConfirmarActionPerformed
    public boolean BuscarActividad(Actividades ObjAct) {
        Actividades ObjAux = new Actividades();
        ObjAux = ObjLogAct.BuscarActividad(ObjAct);

        if (ObjAux.getNombreActividad() != null) // si el objeto nombreactividad es tiene null enviará true para q pueda registrar.
        {
            return false;// está ocuapado, ya está registrado.
        } else {
            return true;// Se puede registrar.

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIU_CrearActividadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIU_CrearActividadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIU_CrearActividadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIU_CrearActividadExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIU_CrearActividadExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonValidar;
    private javax.swing.JTextField NombreActividad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBotonCancelar;
    private javax.swing.JButton jBotonConfirmar;
    private javax.swing.JButton jBotonCrearActividad;
    private javax.swing.JButton jBotonSalir;
    private javax.swing.JComboBox<String> jComboBoxOpicionActividad;
    private com.toedter.calendar.JDateChooser jFechaFin;
    private com.toedter.calendar.JDateChooser jFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonConAporteEconómico;
    private javax.swing.JRadioButton jRadioButtonSinAporteEconómico;
    private javax.swing.JTextField jTextAporteEconomico;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
