/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Estudiante;
import Clases.GradoParalelo;
import Clases.Materia;
import Clases.Matricula;
import Clases.OfertaAcademica;
import Clases.Representante;
import Logica.LogicaEstudiante;
import Logica.LogicaMatricula;
import Logica.LogicaOfertaAcademica;
import Logica.LogicaParalelo;
import Logica.LogicaRepresentante;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import static java.awt.SystemColor.text;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class GUI_Matricula extends javax.swing.JFrame {

    Representante ObjRepresentante = new Representante();
    LogicaRepresentante ObjLogRep = new LogicaRepresentante();
    Estudiante ObjEstudiante = new Estudiante();
    LogicaEstudiante ObjLogEst = new LogicaEstudiante();
    GUI_CrearRepresentante ObjCrearRep = new GUI_CrearRepresentante();
    GradoParalelo ObjGradoParalelo = new GradoParalelo();
    LogicaMatricula objLogicaGP = new LogicaMatricula();
    Matricula ObjMat = new Matricula();
    OfertaAcademica ObjOA = new OfertaAcademica();
    LogicaOfertaAcademica ObjLOA = new LogicaOfertaAcademica();

    /**
     * Creates new form GUI_RegistroActividades
     */
    public GUI_Matricula() {
        initComponents();

        setLocationRelativeTo(null);

        ObjGradoParalelo.setGrado(Integer.parseInt(this.jComboBox2.getSelectedItem().toString()));
        CargarParalelos(ObjGradoParalelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(49, 147, 176));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("SISTEMA DE MATRICULACIÓN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel8)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(49, 147, 176));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 17, -1, 510));

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        jButton3.setText("Registrar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Graduation Cap_96px.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Microsoft Access_96px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 110, 115));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdMateria", "Nombre", "Horas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 510, 180));

        jLabel9.setText("Paralelo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel14.setText("Grado");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel20.setText("Se registará en:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel3.setText("Edad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel23.setText("Cédula:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jTextField1.setEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 158, -1));

        jTextField3.setEnabled(false);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 50, -1));

        jTextField5.setEnabled(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 158, -1));

        jLabel24.setText("Dirección:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 260, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel7.setText("Cédula Representante:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, -1));

        jLabel5.setText("ID Representante:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 100));

        jTextField2.setEnabled(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 158, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("REPRESENTANTE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("ESTUDIANTE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("DATOS GRADO PARALELO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        GIU_Secretaria ObjIA = new GIU_Secretaria();
        int x = JOptionPane.showConfirmDialog(null, "¿Desea regresar?", "Los datos ingresados no se guardarán", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            ObjIA.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        ObjGradoParalelo.setGrado(Integer.parseInt(this.jComboBox2.getSelectedItem().toString()));
        CargarParalelos(ObjGradoParalelo);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:

        this.jTextField7.setText(jTextField7.getText().trim());

        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo números.");
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        ObjRepresentante.setCedula((this.jTextField7.getText().replaceAll("", "")));

        try {
            if (jTextField7.getText().length() == 0 || " ".equals(jTextField7.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese un número de cédula.");
            } else {
                ObjRepresentante = ObjLogRep.BuscarRepresentante(ObjRepresentante);
                if (ObjRepresentante.getCedula().equals(this.jTextField7.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "El representante es: " + ObjRepresentante.getNombre() + " " + ObjRepresentante.getApellido());
                    this.jTextField4.setText(String.valueOf(ObjRepresentante.getIdRepresentante()));
                    this.jTextField1.setEnabled(true);
                    this.jTextField2.setEnabled(true);
                    this.jTextField3.setEnabled(true);
                    this.jTextField5.setEnabled(true);
                    this.jTextField6.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El representante no está registrado.");
                    dispose();
                    ObjCrearRep.setVisible(true);
                    ObjCrearRep.jTextField10.setText(this.jTextField7.getText());
                }
            }

        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(rootPane, "El representante no está registrado.");
            dispose();
            ObjCrearRep.setVisible(true);
            ObjCrearRep.jTextField10.setText(this.jTextField7.getText());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (this.jTextField1.getText().isEmpty() || this.jTextField2.getText().isEmpty() || this.jTextField5.getText().isEmpty()
                || this.jTextField6.getText().isEmpty() || this.jTextField3.getText().isEmpty()) {
            int contador = 0;
            String In = "";
            String CamposVacios = "";
            if (this.jTextField1.getText().isEmpty()) {
                CamposVacios += "\n - Nombre";
                contador++;
            }
            if (this.jTextField2.getText().isEmpty()) {
                CamposVacios += "\n - Apellido";
                contador++;
            }
            if (this.jTextField5.getText().isEmpty()) {
                CamposVacios += "\n - Cédula";
                contador++;
            }
            if (this.jTextField6.getText().isEmpty()) {
                CamposVacios += "\n - Dirección";
                contador++;
            }
            if (this.jTextField3.getText().isEmpty()) {
                CamposVacios += "\n - Edad";
                contador++;
            }

            if (contador > 1) {
                In = ("Campos vacíos: " + CamposVacios);
            } else {
                In = "Campo vacío: " + CamposVacios;
            }

            JOptionPane.showMessageDialog(rootPane, In);
        } else {
            ObjEstudiante.setNombre(this.jTextField1.getText());
            ObjEstudiante.setApellido(this.jTextField2.getText());
            ObjEstudiante.setCedula(this.jTextField5.getText());
            ObjEstudiante.setDireccion(this.jTextField6.getText());
            ObjEstudiante.setEdad(Integer.parseInt(this.jTextField3.getText()));

            ObjRepresentante.setCedula(this.jTextField7.getText());

            ObjRepresentante = ObjLogRep.BuscarRepresentante(ObjRepresentante);

            ObjEstudiante.setRepresentante(ObjRepresentante);

            if (ObjLogEst.InsertarEstudiante(ObjEstudiante)) {

                LogicaParalelo ObjLP = new LogicaParalelo();

                ObjMat.setFecha(getFechaActual());
                ObjMat.setNumMatricula(1);

                ObjEstudiante.setCedula(this.jTextField5.getText());
                ObjMat.setEstudiante(ObjEstudiante);

                ObjGradoParalelo.setParalelo(this.jComboBox3.getSelectedItem().toString());

                ObjGradoParalelo = ObjLP.BuscarParaleloGrado(ObjGradoParalelo.getGrado(), ObjGradoParalelo.getParalelo());

                ObjOA.setIdGradoParalelo(ObjGradoParalelo);

                ObjOA = ObjLOA.BuscarIdOfertaAcademica(ObjOA);

                System.out.println(ObjOA.getIdOfertaAcademica());

                ObjMat.setOfertaAcademica(ObjOA);

                if (objLogicaGP.MatricularEstudiante(ObjMat)) {
                    JOptionPane.showMessageDialog(rootPane, "Estudiante matriculado correctamente");
                    this.imprimirPDF();
                    //Mostrar Oferta Académica
                    ObjGradoParalelo.setGrado(Integer.parseInt(this.jComboBox2.getSelectedItem().toString()));
                    ObjGradoParalelo.setParalelo(this.jComboBox3.getSelectedItem().toString());
                    ListarMateriasAgregadas();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error");

                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Los datos del estudiante no están llenados correctamente");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo números.");
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo números.");
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_jTextField6KeyPressed

    public void HabilitarBoton() {
        if (this.jTextField1.getText().length() != 0 && this.jTextField2.getText().length() != 0
                && this.jTextField3.getText().length() != 0 && this.jTextField5.getText().length() != 0
                && this.jTextField6.getText().length() != 0) {
            this.jButton3.setEnabled(true);
        }
    }

    public void ListarMateriasAgregadas() {
        ArrayList<Materia> arrayListMaterias = new ArrayList<Materia>();
        LogicaOfertaAcademica objLogicaOfertaAcademica = new LogicaOfertaAcademica();

        arrayListMaterias = objLogicaOfertaAcademica.BuscarOfetaAcademica(ObjGradoParalelo);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Horas");

        for (Materia objMateria : arrayListMaterias) {
            Object[] fila = new Object[3];
            fila[0] = objMateria.getIdMateria();
            fila[1] = objMateria.getNombreMateria();
            fila[2] = objMateria.getHoras();
            modelo.addRow(fila);
        }
        this.jTable1.setModel(modelo);

    }
    public void imprimirPDF() {

        Document document = new Document(PageSize.A5, 0, 0, 0, 0);
        String fechaAct = this.getFechaActual();
        
        try {

            // El archivo pdf que vamos a generar
            FileOutputStream fileOutputStream = new FileOutputStream(
                    "C:\\Users\\Ricardo\\Desktop\\ProyectoEscuela\\reportePDFDatoJava.pdf");

            // Obtener la instancia del PdfWriter
            PdfWriter.getInstance(document, fileOutputStream);

            // Abrir el documento
            document.open();

            Image image = null;

            // Obtenemos el logo de datojava
            image = Image.getInstance("C:\\Users\\Ricardo\\Desktop\\ProyectoEscuela\\fotop.png");
            image.scaleAbsolute(350f, 150f);

            // Crear las fuentes para el contenido y los titulos
            Font fontContenido = FontFactory.getFont(
                    FontFactory.TIMES_ROMAN.toString(), 10, Font.NORMAL,
                    BaseColor.DARK_GRAY);
            Font fontTitulos = FontFactory.getFont(
                    FontFactory.TIMES_ROMAN, 11, Font.NORMAL,
                    BaseColor.BLACK);

            // Creacion de una tabla
            PdfPTable table = new PdfPTable(1);

            // Agregar la imagen anterior a una celda de la tabla
            PdfPCell cell = new PdfPCell(image);

            // Propiedades de la celda
            cell.setColspan(5);
            cell.setBorderColor(BaseColor.WHITE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);

            // Agregar la celda a la tabla
            table.addCell(cell);

            // Agregar la tabla al documento
            document.add(table);

            // Cargar otra imagen   this.jteElemBus.getText()
            // Agregar la imagen
            // Creacion del parrafo
            Paragraph paragraph = new Paragraph();

            paragraph.add(new Phrase("      1.  Nombre y direccion", fontTitulos));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("                    Nombre :    " + ObjRepresentante.getNombre(), fontContenido));
            paragraph.add(new Phrase("\n                    Apellido :    " + ObjRepresentante.getApellido(), fontContenido));
            paragraph.add(new Phrase("\n                    Cedula:    " + ObjRepresentante.getCedula(), fontContenido));
            paragraph.add(new Phrase("\n                    Fecha :    " + fechaAct , fontContenido));
            paragraph.add(new Phrase("\n                    Correo:    " + ObjRepresentante.getCorreo(), fontContenido));
            
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("      2.  Detalle ", fontTitulos));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("                 Año lectivo:    2018 " , fontContenido));
            paragraph.add(new Phrase("\n                       Codigo:      " , fontContenido));
            paragraph.add(new Phrase("\n                      Alumno:      " + ObjEstudiante.getNombre() +" "+ObjEstudiante.getApellido(), fontContenido));
            paragraph.add(new Phrase("\n                      Cedula:       " + ObjEstudiante.getCedula(), fontContenido));
            paragraph.add(new Phrase("\n                      Grado:        " +  ObjGradoParalelo.getGrado(),fontContenido));
            paragraph.add(new Phrase("\n                    Paralelo:      " + ObjGradoParalelo.getParalelo(), fontContenido));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("      3.  Costos ", fontTitulos));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("                        Valor:     100$    ", fontContenido));
            paragraph.add(new Phrase("\n                        I.V.A:     12%  ", fontContenido));
            paragraph.add(new Phrase("\n                        Total:     112$ (Ciento doce dólares)    " , fontContenido));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("      4.  Firman conformes", fontTitulos));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("                                                    Cliente                                 Scretaria/o", fontTitulos));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase(Chunk.NEWLINE));
            paragraph.add(new Phrase("\n                                                   - firma -                                    -firma-", fontTitulos));
            paragraph.add(new Phrase(Chunk.NEWLINE));
 
            // Agregar el parrafo al documento
            document.add(paragraph);

            // La lista final
            // Cerrar el documento
            document.close();

            // Abrir el archivo
            File inFile = new File("C:\\Users\\Ricardo\\Desktop\\ProyectoEscuela\\reportePDFDatoJava.pdf");
            // HAY QUE CAMBIAR LA RUTA DE LA CARPETA CONTENEDORA DE RECUPERACION.
            Date fecha = new Date();

            int mes = fecha.getMonth() + 1;
            File outFile = new File("C:\\Users\\Ricardo\\Desktop\\ProyectoEscuela\\PDFs\\" + mes + "Rec_" + ObjRepresentante.getNombre() + "_" + ObjRepresentante.getApellido() + "_" + fecha.getDay() + fecha.getHours() + fecha.getMinutes() + fecha.getSeconds() + ".pdf");

            FileInputStream in = new FileInputStream(inFile);
            FileOutputStream out = new FileOutputStream(outFile);

            int c;

            while ((c = in.read()) != -1) {
                out.write(c);
            }
            in.close();
            out.close();

            Desktop.getDesktop().open(outFile);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Matricula().setVisible(true);
            }
        });
    }

    public void CargarParalelos(GradoParalelo GradoSelect) {
        ArrayList<GradoParalelo> ArrayPar = new ArrayList<GradoParalelo>();
        GradoParalelo objGP = new GradoParalelo();

        try {
            ArrayPar = objLogicaGP.ObtenerParalelos(GradoSelect);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
            System.err.println(e);
        }

        DefaultComboBoxModel dlm = new DefaultComboBoxModel();

        for (GradoParalelo c : ArrayPar) {
            dlm.addElement(c.getParalelo());
        }
        this.jComboBox3.setModel(dlm);
    }

    public static String getFechaActual() {
        java.util.Date ahora = new java.util.Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
        return formateador.format(ahora);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
