/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.GradoParalelo;
import Clases.Materia;
import Clases.OfertaAcademica;
import Data.DataMateria;
import Logica.LogicaMateria;
import Logica.LogicaMatricula;
import Logica.LogicaOfertaAcademica;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GUI_CrearOfertarAcademica extends javax.swing.JFrame {

    /**
     * Creates new form GUI_OfertarMateria
     */
    OfertaAcademica objOfertaAcademica = new OfertaAcademica();
    Materia objMateria = new Materia();
    DataMateria objDataMateria = new DataMateria();
    LogicaMateria objLogicaMateria = new LogicaMateria();
    LogicaOfertaAcademica objLogicaOfertaAcademica = new LogicaOfertaAcademica();
    GradoParalelo objGradoParalelo = new GradoParalelo();
    GradoParalelo ObjGradoParalelo = new GradoParalelo();
    
    LogicaMatricula objLogicaGP = new LogicaMatricula();

    ArrayList<Materia> arrayListMaterias = new ArrayList<Materia>();
    ArrayList<GradoParalelo> arrayListGradoParalelos = new ArrayList<GradoParalelo>();

    String materiaId;

    public GUI_CrearOfertarAcademica() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        ListarMaterias();
        this.jBEliminar.setEnabled(false);      
        
        ObjGradoParalelo.setGrado(Integer.parseInt(this.jCBGrado.getSelectedItem().toString()));
        CargarParalelos(ObjGradoParalelo);
        ObjGradoParalelo.setParalelo(this.jComboBox1.getSelectedItem().toString());        
        ListarMateriasAgregadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        jbtnAgregar = new javax.swing.JButton();
        jCBGrado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMateriasAgregadas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLGrado = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(49, 147, 176));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("OFERTA ACADEMICA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 657, -1));

        jTableMaterias = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            };
        };
        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdMateria", "Nombre Materia", "Horas"
            }
        ));
        jTableMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMaterias.setEnabled(false);
        jTableMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 521, 99));

        jbtnAgregar.setBackground(new java.awt.Color(49, 147, 176));
        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 212, 86, -1));

        jCBGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jCBGrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBGradoMouseClicked(evt);
            }
        });
        jCBGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGradoActionPerformed(evt);
            }
        });
        jPanel1.add(jCBGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 138, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("GRADO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 103, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("MATERIAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 68, -1, -1));

        jTableMateriasAgregadas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            };
        };
        jTableMateriasAgregadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "idMateria", "Nombre Materia"
            }
        ));
        jTableMateriasAgregadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMateriasAgregadasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMateriasAgregadas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 521, 104));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Materias Agregadas al Curso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 212, 266, -1));

        jLGrado.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLGrado.setText("1");
        jPanel1.add(jLGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 38, -1));

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 268, 86, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 169, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("'A'");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        // TODO add your handling code here:
        String gradoParalelo = (String) this.jCBGrado.getSelectedItem();
        int row = this.jTableMaterias.getSelectedRow();
        String materia = this.jTableMaterias.getValueAt(row, 0).toString();
        objGradoParalelo.setIdGradoParalelo(Integer.parseInt(gradoParalelo));
        objMateria.setIdMateria(Integer.parseInt(materia));
        objMateria.getIdMateria();
        objGradoParalelo.setGrado(Integer.parseInt(gradoParalelo));
        objGradoParalelo.getGrado();
        if (objLogicaOfertaAcademica.BuscarIdMateria(objMateria, objGradoParalelo)) {
            JOptionPane.showMessageDialog(rootPane, "Ya esta registrado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Correcto");
            objLogicaOfertaAcademica.InsertarOfertaAcademica(objGradoParalelo, objMateria);
        }
        ListarMateriasAgregadas();
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jCBGradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBGradoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jCBGradoMouseClicked

    private void jCBGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGradoActionPerformed
        
        ObjGradoParalelo.setGrado(Integer.parseInt(this.jCBGrado.getSelectedItem().toString()));
        CargarParalelos(ObjGradoParalelo);
        
        ObjGradoParalelo.setParalelo(this.jComboBox1.getSelectedItem().toString());
        this.jTableMaterias.setEnabled(true);
        
        ListarMateriasAgregadas();
        this.jbtnAgregar.setEnabled(true);
        this.jLGrado.setText(String.valueOf(ObjGradoParalelo.getGrado()));
        this.jLabel3.setText("'"+ ObjGradoParalelo.getParalelo() +"'");
    }//GEN-LAST:event_jCBGradoActionPerformed
    public void ListarMateriasAgregadas() {
        arrayListMaterias = objLogicaOfertaAcademica.BuscarOfetaAcademica(ObjGradoParalelo);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Horas");

        for (Materia objMateria : arrayListMaterias) {
            Object[] fila = new Object[3];
            fila[0] = objMateria.getIdMateria();
            fila[1] = objMateria.getNombreMateria();
            fila[2] = objMateria.getHoras();
            modelo.addRow(fila);
        }
        this.jTableMateriasAgregadas.setModel(modelo);

    }
    private void jTableMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMateriasMouseClicked
        
        this.jBEliminar.setEnabled(false);
        this.jbtnAgregar.setEnabled(true);
    }//GEN-LAST:event_jTableMateriasMouseClicked

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed

        int row = this.jTableMateriasAgregadas.getSelectedRow();
        String gradoParalelo = (String) this.jCBGrado.getSelectedItem();
        String materia = this.jTableMateriasAgregadas.getValueAt(row, 0).toString();
        objMateria.setIdMateria(Integer.parseInt(materia));
        objMateria.getIdMateria();
        objGradoParalelo.setIdGradoParalelo(Integer.parseInt(gradoParalelo));
        objGradoParalelo.setGrado(Integer.parseInt(gradoParalelo));
        objGradoParalelo.getGrado();

        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la materia?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            try {
                objLogicaOfertaAcademica.EliminarAlumnoActividad(objMateria, objGradoParalelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "La materia no se puede eliminar");
            }finally{
                JOptionPane.showMessageDialog(rootPane, "La materia no se puede eliminar porque hay estudiantes matriculados");
            }
        }

    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTableMateriasAgregadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMateriasAgregadasMouseClicked
        // TODO add your handling code here:
        this.jBEliminar.setEnabled(true);
        this.jbtnAgregar.setEnabled(false);
    }//GEN-LAST:event_jTableMateriasAgregadasMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        ObjGradoParalelo.setParalelo(this.jComboBox1.getSelectedItem().toString());
        this.jTableMaterias.setEnabled(true);
        
        ListarMateriasAgregadas();
        this.jbtnAgregar.setEnabled(true);
        this.jLGrado.setText(String.valueOf(ObjGradoParalelo.getGrado()));
        this.jLabel3.setText("'"+ ObjGradoParalelo.getParalelo() +"'");        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GIU_Administrador ObjIA = new GIU_Administrador();
        int x = JOptionPane.showConfirmDialog(null, "¿Desea regresar?", "Los datos ingresados no se guardarán", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            ObjIA.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void ListarMaterias() {
        ArrayList<Materia> ArrayMaterias = new ArrayList<Materia>();
        ArrayMaterias = objLogicaMateria.ListarMaterias();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("idMateria");
        modelo.addColumn("Nombre");
        modelo.addColumn("Horas");

        for (Materia objMateria : ArrayMaterias) {
            Object[] fila = new Object[3];
            fila[0] = objMateria.getIdMateria();
            fila[1] = objMateria.getNombreMateria();
            fila[2] = objMateria.getHoras();
            modelo.addRow(fila);
        }
        this.jTableMaterias.setModel(modelo);

    }

    public void LlenarTablaMaterias() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Horas");
        modelo.addColumn("Grado");
        modelo.addColumn("Paralelo");
        modelo.addColumn("Profesor");
        for (Materia arrayListMateria : arrayListMaterias) {
            Object[] fila = new Object[5];
            fila[0] = arrayListMateria.getNombreMateria();
            fila[1] = arrayListMateria.getHoras();
            fila[2] = arrayListMateria.getGradoparalelo().getGrado();
            fila[3] = arrayListMateria.getGradoparalelo().getParalelo();
            fila[4] = arrayListMateria.getProfesor().getNombre();

            modelo.addRow(fila);
        }
        this.jTableMateriasAgregadas.setModel(modelo);
    }
    public void CargarParalelos(GradoParalelo GradoSelect) {
        ArrayList<GradoParalelo> ArrayPar = new ArrayList<GradoParalelo>();
        GradoParalelo objGP = new GradoParalelo();

        try {
            ArrayPar = objLogicaGP.ObtenerParalelos(GradoSelect);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
            System.err.println(e);
        }

        DefaultComboBoxModel dlm = new DefaultComboBoxModel();

        for (GradoParalelo c : ArrayPar) {
            dlm.addElement(c.getParalelo());
        }
        this.jComboBox1.setModel(dlm);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearOfertarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearOfertarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearOfertarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearOfertarAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CrearOfertarAcademica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBGrado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLGrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JTable jTableMateriasAgregadas;
    private javax.swing.JButton jbtnAgregar;
    // End of variables declaration//GEN-END:variables
}
